### PR TITLE
chore: add type property under conditional exports in package.json

### PR DESCRIPTION
**Pull request by minenwerfer**
This PR solves a tsc problem that occurs when `"module": "nodenext"` is set in tsconfig.json (I couldn't figure why exactly). Setting `compilerOptions.paths` also solves the problem, but I think it would be more convenient if this was changed in the upstream.

Without any changes:

```
Error: src/property.ts(1,35): error TS7016: Could not find a declaration file for module '@phosphor-icons/core'. 
'/home/runner/work/sonata-api/sonata-api/packages/types/node_modules/@phosphor-icons/core/dist/index.umd.js' implicitly has an 'any' type.
```

### CODE REVIEW

**Comment by minenwerfer** [comment]
I think I messed with the previous commits, I'll open another PR if you'd prefer.

**Review by rektdeckard — APPROVED** [review]
Looks good, thanks for the submission!

**Comment by rektdeckard** [comment]
Can't see any conflicts, but unable to rebase and merge. Would you resubmit?

**Comment by minenwerfer** [comment]
> Can't see any conflicts, but unable to rebase and merge. Would you resubmit?

Hey, I see you already pushed this to main, should the PR be closed now?

**Comment by rektdeckard** [comment]
Yep, sorry to jump the gun on you! Thanks for the fix anyway.

**Pull request closed without merging**
